org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.2-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=See every mob's health in style. In the HUD and in-world. Clean, colorful, and customizable!
mod.group=fuzs.healthbars
mod.id=healthbars
mod.license=MPL-2.0
mod.name=Health Bars
mod.version=26.2.1

dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.curseforge.id=1367734
distributions.curseforge.slug=health-bars
distributions.github.slug=health-bars
distributions.modrinth.id=A3VSiTms
distributions.modrinth.slug=health-bars

environments.client=required
environments.server=unsupported
